### ISSUE TITLE
[ Backend ] : API Implementation for Task Creation

### ISSUE THREAD

**Issue by JavidSumra** [sayan404/TaskPulse#11]
# API Implementation Request: Task Creation

### 1. Endpoint Information
- **API Endpoint URL:** `/api/v1/tasks/create`
- **HTTP Method:** `POST`
- **Authentication:** `JWT Authentication`

## 2. Request Payload 
- **Request Format:** JSON

```json
{
  "taskName": "Example Task",
  "dueDate": "2024-02-01",
  "assignee": "John Doe",
  "priority": "High"
}
```

### 3. Response Format
{
  "taskId": "123456",
  "status": "success",
  "message": "Task created successfully",
  "data": {
    "taskName": "Example Task",
    "dueDate": "2024-02-01",
    "assignee": "John Doe",
    "priority": "High"
  }
}

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir I Would Like to Work on This Issue under JWOC 2024

**Comment by sayan404** [comment]
okay, I am assigning this issue to you under JWoC. @JavidSumra

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir Could you please let me know what kind of parameters need to be stored?

**Comment by JavidSumra** [comment]
And please Add Labels @sayan404 Sir

**Comment by sayan404** [comment]
> And please Add Labels @sayan404 Sir

yea , have already done that .

**Comment by JavidSumra** [comment]
> Hey @sayan404 Sir Could you please let me know what kind of parameters need to be stored?

??? @sayan404 Sir

**Comment by sayan404** [comment]
> Hey @sayan404 Sir Could you please let me know what kind of parameters need to be stored?

I can suggest that the must-have fields in the task schema are, TaskName, Description, Priority (in number) , Deadline Date (optional), Image(optional), creation date, and comments section.
You can modify on this. @JavidSumra
