### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by devanshrajput07** [sayan404/TaskPulse#13]
There are many typo in the code. Assign me to remove all typos and make the code perfect.

**Comment by sayan404** [comment]
Can you please attach a screenshot of any two typos?  @devanshrajput07

**Comment by devanshrajput07** [comment]
![Screenshot (3)](https://github.com/sayan404/TaskPulse/assets/113511553/7d2572f0-23f4-4ee0-98a0-503aee26752f)
@sayan404 At all the places, the word 'Charecter' should be replaced with 'Character'. Additionally, the all messages should be changed for good practice. Example:- 'Please Enter A Valid Email' should be changed to 'Please enter a valid email'.

**Comment by sayan404** [comment]
okay , I am assigning this issue to you under JWoC. @devanshrajput07

**Comment by devanshrajput07** [comment]
#20
