### ISSUE TITLE
[Backend] API Endpoint For Tasks Delete

### ISSUE THREAD

**Issue by JavidSumra** [sayan404/TaskPulse#18]
# API Implementation Request: Task Deletion

### 1. Endpoint Information
- **API Endpoint URL:** `/api/v1/tasks/delete/:id`
- **HTTP Method:** `DELETE`
- **Authentication:** `JWT Authentication`

## 2. Request Payload 
- **Request Format:** JSON

```json
{
  "id": 5f92cdce0cf217478ba93563
}
```

### 3. Response Format
```json
{
  success:true,
  message:"Deleted Successfully"
}
```

**Comment by JavidSumra** [comment]
Assign me this issue under JWOC 2024

**Comment by sayan404** [comment]
ok, I am assigning this issue to you under JWoC. @JavidSumra
