### ISSUE TITLE
User Authentication (Login and Signup) with JWT

### ISSUE THREAD

**Issue by JavidSumra** [sayan404/TaskPulse#2]
**Description:**

This enhancement introduces user authentication capabilities, including login and signup functionalities, to the Task Pulse project. The authentication mechanism is implemented using JSON Web Tokens (JWT) for secure and stateless communication between the client and the server.

**Key Features:**

1. **User Signup:**
   - Users can now create a new account by providing essential information such as username, email, and password.
   - Passwords are securely hashed and stored in the database to ensure confidentiality.

2. **User Login:**
   - Registered users can log in securely with their credentials.
   - Upon successful login, the server generates a JWT token, which is then sent to the client for future authentication.

3. **JWT Token Authentication:**
   - JWT tokens are utilized for subsequent user authentication after login.
   - The token is securely transmitted in the authorization header of API requests to validate user identity.

4. **Token Expiry and Refresh:**
   - JWT tokens have a defined expiration time to enhance security.
   - Users can refresh their tokens by making a secure refresh token request, maintaining a seamless user experience.

5. **Security Measures:**
   - Passwords are hashed using industry-standard algorithms to protect user credentials.
   - Token transmission is encrypted to prevent unauthorized access.

**Implementation Steps:**

1. Integrate user signup API endpoint to handle user registration.
2. Implement user login API endpoint to authenticate users and generate JWT tokens.
3. Develop token refresh mechanism to extend user sessions.
4. Securely handle and store user passwords using appropriate hashing techniques.
5. Enhance API routes to check for valid JWT tokens during user interactions.

**Dependencies:**
- Ensure the project includes necessary libraries for JWT implementation and password hashing.

This enhancement enhances Task Pulse's security and user management, providing a foundation for more sophisticated features in future releases.

**Comment by JavidSumra** [comment]
I would like to work on that issue under JWOC

**Comment by sayan404** [comment]
This mechanism is already implemented. Please take a `git pull origin main` and make sure you are in the latest pull before raising any issue . @JavidSumra
