### ISSUE TITLE
Backend: Enhancing Security with Regex for Name, Email, and Password Validation in Signup Process

### ISSUE THREAD

**Issue by devanshrajput07** [sayan404/TaskPulse#22]
In order to improve security measures within our signup process, we need to implement robust regular expressions (regex) for validating user inputs such as name, email, and password. This enhancement will help mitigate potential security risks by ensuring that users adhere to stricter guidelines when creating their accounts.

1. Implement Regex for Name Validation:
Define regex pattern for validating names, ensuring it allows only alphabetic characters and possibly special characters like hyphens or apostrophes for certain cases (e.g., O'Brien).
Update signup form to enforce this regex pattern for the name field.
Provide appropriate error messages for users if their input doesn't match the regex pattern.

2. Implement Regex for Email Validation:
Develop a regex pattern for validating email addresses, adhering to standard email format rules (e.g., username@domain.com).
Integrate this regex pattern into the signup form for validating email inputs.
Display clear error messages for incorrect email formats.

3. Implement Regex for Password Validation:
Create a regex pattern for enforcing strong password requirements, including a mix of uppercase and lowercase letters, numbers, and special characters.
Update the password field in the signup form to enforce this regex pattern.
Provide informative messages about the password criteria to users attempting to sign up.

4. Update Signup Flow:
Modify the signup process to incorporate the new regex validations for name, email, and password.
Ensure that users are informed about the specific requirements for each input field during the signup process.
Test the updated signup flow thoroughly to verify that regex validations are working as intended.

5. Integration with Existing Security Measures:
Ensure that the regex validations complement existing security measures within the application.
Coordinate with the security team to align regex patterns with overall security protocols.

**Comment by devanshrajput07** [comment]
Assign this to me @sayan404

**Comment by sayan404** [comment]
Okay, I am assigning this issue to you under JWoC . @devanshrajput07

**Comment by devanshrajput07** [comment]
#26
