### ISSUE TITLE
[ Backend ] - Task Details Update Route 

### ISSUE THREAD

**Issue by JavidSumra** [sayan404/TaskPulse#24]
# API Implementation Request: Task Details Updation

### 1. Endpoint Information
- **API Endpoint URL:** `/api/v1/tasks/update/:id`
- **HTTP Method:** `PUT`
- **Authentication:** `JWT Authentication`

## 2. Request Payload 
- **Request Format:** JSON

```json
{
  "taskName": "Example Task",
  "dueDate": "2024-02-01",
  "assignee": "John Doe",
  "priority": "High"
}
```

### 3. Response Format
```json
{
  "taskId": "123456",
  "status": "success",
  "message": "Task Updated successfully",
  "data": {
    "taskName": "Example Task",
    "dueDate": "2024-02-01",
    "assignee": "John Doe",
    "priority": "High"
  }
}
```

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir I Would Like to Work on This Issue Under JWOC 2024

**Comment by sayan404** [comment]
Okay I am assigning this issue to you under JWoC. @JavidSumra
