### ISSUE TITLE
[Backend]: Add Update Password functionality

### ISSUE THREAD

**Issue by devanshrajput07** [sayan404/TaskPulse#28]
**API Implementation : Update Password**

1. Endpoint Information
API Endpoint URL: /api/v1/users/password/update
HTTP Method: PUT

2. Request Payload
Request Format: JSON
```
{
    "oldPassword": "TJTBJd123@@",
    "password": "FHhkbskjlj15245##"
}
```

3. Response Format
```
{
    "success": true,
    "message": "Password updated successfully",
    "user": {
        "_id": "65bbcd0b561062b186858e04"
    }
}
```

**Comment by devanshrajput07** [comment]
Assign me @sayan404 .

**Comment by sayan404** [comment]
okay , I am assigning this issue to you . @devanshrajput07

**Comment by devanshrajput07** [comment]
#30
