### ISSUE TITLE
Bug: Currently, we can access the /login route even in a logged-in situation.

### ISSUE THREAD

**Issue by sayan404** [sayan404/TaskPulse#29]
### Bug 
 Currently, we can access the /login route even in a logged-in situation.

### Expected behavior 
 The /login route should not be accessible when I have a valid JWT and I am also in a logged situation. 

### Grab the issue
- to grab the issue comment below `I want to contribute in this issue under JWoC. Assign me this issue.`
### Contributor Guideline
- Read the README.md file before contributing

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir I Would Like to Work on This issue Under JWOC 2024

**Comment by sayan404** [comment]
okay, assigning this issue to you @JavidSumra
