### ISSUE TITLE
Improve UI in mobile view in Login page

### ISSUE THREAD

**Issue by sarthakroy107** [sayan404/TaskPulse#3]
Issue: While using mobile view, login page becomes unusable.
![Screenshot_20240117_202040](https://github.com/sayan404/TaskPulse/assets/95567641/cbadc1bb-51cb-4375-b377-c3976545ddcd)

Fix: Improve layout.

I would like to work on this issue under jwoc

**Comment by sayan404** [comment]
I am assigning this issue to you. Happy coding 🚀.
