### ISSUE TITLE
[Backend]: Add Update User Details functionality

### ISSUE THREAD

**Issue by devanshrajput07** [sayan404/TaskPulse#31]
**API Implementation : Update User Details**

1. Endpoint Information
API Endpoint URL: /api/v1/users/me/update
HTTP Method: PUT

Request Payload
2. Request Format: JSON

```
{
    "name":"Abcdefg",
    "email":"abcdef@gmail.com"
}
```
3. Response Format

```
{
    success: true,
    message: "Profile Updated Successfully",
    user: {
      _id: user._id,
      username: user.name,
      email: user.email,
    },
  }
```

**Comment by sayan404** [comment]
okay assigning this issue to you @devanshrajput07

**Comment by devanshrajput07** [comment]
#32
