### ISSUE TITLE
[BACKEND] : Status Tracking: 

### ISSUE THREAD

**Issue by Anushkabh** [sayan404/TaskPulse#34]
Categorize tasks based on their status (e.g., To-Do, In Progress, Completed) to monitor progress at a glance.
For this feature task model should include this

status: {
        type: String,
        enum: ["To-Do", "In Progress", "Completed"],
        default: "To-Do",
        required: true,
      },

**Comment by Anushkabh** [comment]
@sayan404 kindly assign this issue under JWOC'24

**Comment by sayan404** [comment]
go ahead @Anushkabh  .

**Comment by Anushkabh** [comment]
i have completed kindly merge @sayan404  #35
