### ISSUE TITLE
API to Delete User Account

### ISSUE THREAD

**Issue by JavidSumra** [sayan404/TaskPulse#37]
1. **Endpoint Information**
   - API Endpoint URL: `/api/v1/users/accounts/delete/:id`
   - HTTP Method: DELETE
   - Authentication: JWT Authentication

2. **Request Payload**
   - Request Format: JSON
   - No request payload is necessary for account deletion as the user ID is provided in the URL path.

3. **Response Format**
   - Success Response:
     ```
     {
       "accountId": "789012",
       "status": "success",
       "message": "Account deleted successfully",
       "data": null
     }
     ```
   - Error Response (if account does not exist):
     ```
     {
       "status": "error",
       "message": "Account not found",
       "data": null
     }
     ```

This API allows users to delete their accounts by providing the account ID in the URL path. Upon successful deletion, it returns a success response with a message confirming the deletion. If the account does not exist, it returns an error response indicating that the account was not found.

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir Please Assign This Issue to me Under JWOC 2024

**Comment by sayan404** [comment]
assigning @JavidSumra
