### ISSUE TITLE
Bug:"Boost your productivity and take control of your life." written twice at homepage.

### ISSUE THREAD

**Issue by rahat2134** [sayan404/TaskPulse#7]
<img width="645" alt="Screenshot 2024-01-21 at 12 23 23 AM" src="https://github.com/sayan404/TaskPulse/assets/136263179/616dc73c-010f-4193-9bf9-2a3f360145f7">

I will resolve it by either adding or removing it.

**Comment by rahat2134** [comment]
@sayan404 assignt this to me under JWOC.

**Comment by sayan404** [comment]
I have assigned the issue to you. @rahat2134  . Happy Coding 🚀

**Comment by rahat2134** [comment]
thanks

**Comment by rahat2134** [comment]
@sayan404 please check pr .

**Comment by sayan404** [comment]
Yea , have merged your PR. @rahat2134
